---
#------------------------------------------------------------------------------
# Note: Tested on RHEL 7.4
#------------------------------------------------------------------------------
  
- name: Test workflow
  hosts: all
  serial: 1
  
  pre_tasks:
    - debug:
        msg: Test playbook with roles

 #########################################################
 # Return success
 #########################################################
  roles:
    - role: always_true

 #########################################################
 # Return failure, but rescue
 #########################################################
    - role: always_false
