---
#------------------------------------------------------------------------------
# Note: Tested on RHEL 7.4
#------------------------------------------------------------------------------

- name: Run static command
  shell: pwd
